INSERT INTO book (title, synopsis, author, category, publication_year, available) VALUES
                                                                                          ('The Hobbit', 'Bilbo Baggins, a simple hobbit, is thrust into an unexpected adventure when the wizard Gandalf and a company of dwarves recruit him to reclaim their homeland from the dragon Smaug. Along the journey, Bilbo encounters trolls, goblins, elves, and a mysterious creature named Gollum, from whom he obtains a magical ring that grants invisibility. Facing trials and challenges, Bilbo discovers courage he never knew he had and becomes a hero in the process.', 'J.R.R. Tolkien', 'Fantasy', '1937', true),

                                                                                          ('Harry Potter and the Sorcerer''s Stone', 'Harry Potter, an orphaned boy living with his cruel relatives, discovers on his eleventh birthday that he is a wizard. He is invited to attend Hogwarts School of Witchcraft and Wizardry, where he befriends Ron Weasley and Hermione Granger. As he learns magic, Harry uncovers the mystery of the Sorcerer’s Stone, a powerful object that grants immortality, while facing the dark legacy of the evil Lord Voldemort.', 'J.K. Rowling', 'Fantasy', '1997', true),

                                                                                          ('The Name of the Wind', 'Kvothe, a gifted young man, grows up in a troupe of traveling performers. After tragedy strikes and his family is murdered, he survives on the streets before finding his way to the University, where he hones his magical abilities. With a thirst for knowledge and an uncanny talent for storytelling, Kvothe seeks to uncover the truth behind the legendary Chandrian, the mysterious beings responsible for his family’s destruction.', 'Patrick Rothfuss', 'Fantasy', '2007', true),

                                                                                          ('A Game of Thrones', 'In the Seven Kingdoms of Westeros, noble families compete for power in an intricate web of betrayal, war, and political intrigue. The Stark family, led by Eddard Stark, becomes entangled in the dangerous politics of King’s Landing. Meanwhile, across the sea, Daenerys Targaryen, the last surviving heir to the deposed throne, begins her journey to reclaim her birthright. As winter approaches, an ancient and deadly force stirs in the far north.', 'George R.R. Martin', 'Fantasy', '1996', true),

                                                                                          ('Mistborn: The Final Empire', 'In a world ruled by the immortal Lord Ruler, where ash falls from the sky and mist fills the streets, a group of rebels led by Vin, a young street urchin with hidden powers, attempts to overthrow the oppressive regime. As Vin learns to harness her Allomantic abilities, she discovers not only the power to manipulate metals but also the deep and ancient secrets of the empire that could change the world forever.', 'Brandon Sanderson', 'Fantasy', '2006', true),

                                                                                          ('The Wheel of Time: The Eye of the World', 'The first book in the epic Wheel of Time series, where Rand al’Thor, a young man from the remote village of Emond’s Field, finds himself swept up in a world-shaking struggle for power. With the forces of darkness rising, Rand and his companions must travel across the lands, guided by mysterious prophecies, to stop the Dark One from destroying the world. Along the way, they encounter dangerous foes and uncover secrets that will alter the course of history.', 'Robert Jordan', 'Fantasy', '1990', true),

                                                                                          ('The Way of Kings', 'In the shattered world of Roshar, a land ravaged by storms, different factions vie for power while ancient forces stir beneath the surface. Kaladin Stormblessed, a former soldier turned slave, finds himself thrust into a conflict far greater than he could ever imagine. With the help of magical abilities, Kaladin and his companions must navigate through betrayals, wars, and a growing darkness that threatens their world.', 'Brandon Sanderson', 'Fantasy', '2010', true),

                                                                                          ('The Dark Tower: The Gunslinger', 'Roland, the last gunslinger, is on a relentless quest to find the Dark Tower, a mysterious structure that holds the key to saving or destroying all worlds. Along the way, Roland encounters strange characters, from the mysterious man in black to a young boy named Jake, whose fate is intricately linked to Roland’s mission. As Roland’s obsession with the Tower grows, he faces not only external threats but his own inner demons.', 'Stephen King', 'Fantasy', '1982', false),

                                                                                          ('The Priory of the Orange Tree', 'In a world divided by conflict, four kingdoms must confront the ancient and powerful dragons that threaten their survival. The story follows multiple characters, including a dragon-riding queen, a dragon-rider from the East, and a mage who uncovers long-forgotten secrets. Together, they must overcome their fears, prejudices, and past mistakes to unite their people against a force that could destroy everything they know.', 'Samantha Shannon', 'Fantasy', '2019', true),

                                                                                          ('Dune', 'Paul Atreides, heir to the noble House Atreides, is thrust into a battle for control over the desert planet Arrakis, the only source of the valuable spice melange. Betrayed by rival factions, Paul must survive the harsh desert with the help of the Fremen, the native people of Arrakis. As he embraces his destiny, he discovers visions of a future that may change the fate of the universe forever.', 'Frank Herbert', 'Science Fiction', '1965', true),

                                                                                          ('1984', 'In a dystopian future where the totalitarian regime of Big Brother controls every aspect of life, Winston Smith secretly harbors rebellious thoughts against the Party. Living under constant surveillance, he begins a forbidden love affair with Julia, defying the oppressive rules of the state. As Winston seeks the truth about reality and freedom, he is drawn into a dangerous battle against the system that seeks to crush all independent thought.', 'George Orwell', 'Dystopian', '1949', false),

                                                                                          ('To Kill a Mockingbird', 'Set in the racially segregated American South of the 1930s, this novel follows Scout Finch, a young girl growing up in the small town of Maycomb. Through her father, Atticus Finch, a principled lawyer defending a black man accused of a crime he didn’t commit, Scout learns powerful lessons about justice, empathy, and the complexity of human nature in a world filled with prejudice and moral dilemmas.', 'Harper Lee', 'Classic', '1960', true),

                                                                                          ('Pride and Prejudice', 'Elizabeth Bennet, an intelligent and spirited young woman, finds herself at odds with the wealthy and proud Mr. Darcy. As they navigate misunderstandings and societal expectations in 19th-century England, Elizabeth must confront her own prejudices and assumptions about love and class. Through wit, charm, and personal growth, she discovers that first impressions can be deceiving.', 'Jane Austen', 'Romance', '1813', false),

                                                                                          ('The Martian', 'Astronaut Mark Watney is left stranded on Mars after a disastrous mission, presumed dead by his crew. With limited resources, he must use his ingenuity and engineering skills to survive in the harsh Martian environment while awaiting a potential rescue. As he faces one life-threatening challenge after another, humanity unites in an unprecedented effort to bring him home.', 'Andy Weir', 'Science Fiction', '2011', true),

                                                                                          ('Gone Girl', 'Nick Dunne’s life takes a dark turn when his wife, Amy, suddenly goes missing. As the police investigation unfolds, Nick’s lies and secrets paint him as the prime suspect. However, Amy’s meticulously planned disappearance hides shocking revelations that challenge perceptions of truth, marriage, and media manipulation in this psychological thriller filled with unexpected twists.', 'Gillian Flynn', 'Thriller', '2012', false),

                                                                                          ('The Silent Patient', 'Alicia Berenson, a famous painter, is found standing next to her husband’s dead body, covered in blood, and refusing to speak a single word. Institutionalized in a mental facility, she remains silent for years. When Theo Faber, a determined psychotherapist, takes on her case, he becomes obsessed with uncovering the truth behind her silence, leading to a shocking revelation.', 'Alex Michaelides', 'Mystery', '2019', true),

                                                                                          ('The Road', 'In a bleak, post-apocalyptic world where civilization has collapsed, a father and his young son embark on a perilous journey across a devastated landscape. Facing starvation, brutal survivors, and the harsh elements, they cling to hope and the promise of reaching a better place. The novel explores themes of love, survival, and the bond between parent and child in a world stripped of morality.', 'Cormac McCarthy', 'Post-Apocalyptic', '2006', false),

                                                                                          ('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari takes readers on a fascinating journey through the history of humankind, from the emergence of Homo sapiens to the rise of modern civilizations. Through an engaging exploration of anthropology, history, and science, the book examines how human cultures, religions, and economies evolved over thousands of years, shaping the world we live in today.', 'Yuval Noah Harari', 'Non-Fiction', '2011', true),

                                                                                          ('The Catcher in the Rye', 'Holden Caulfield, a disillusioned teenager, recounts his experiences after being expelled from prep school. Wandering through New York City, he grapples with loneliness, identity, and the phoniness of the adult world. Filled with introspective musings and rebellious spirit, Holden’s story remains a timeless reflection on youth, alienation, and the search for authenticity.', 'J.D. Salinger', 'Coming of Age', '1951', true),

                                                                                        ('The Girl with the Dragon Tattoo', 'Lisbeth Salander, a brilliant but troubled hacker, is drawn into a complex investigation alongside journalist Mikael Blomkvist. Together, they uncover the secrets of the Vanger family, whose patriarch’s disappearance decades ago remains a mystery. As they dig deeper into the family’s dark history, they uncover a web of corruption, violence, and secrets that threatens to destroy everyone involved.', 'Stieg Larsson', 'Mystery', '2005', false),

                                                                                        ('Big Little Lies', 'In a seemingly perfect coastal town, three women’s lives intertwine in the midst of a tragedy. Madeline, Celeste, and Jane each have their own struggles—Madeline’s turbulent relationship with her ex-husband, Celeste’s hidden abuse, and Jane’s past trauma. As their children attend the same school, a series of events leads to a violent confrontation, and the women must confront their darkest secrets to uncover the truth.', 'Liane Moriarty', 'Thriller', '2014', true),

                                                                                        -- Historical Fiction
                                                                                        ('All the Light We Cannot See', 'Set during World War II, this novel tells the story of two main characters: Marie-Laure, a blind French girl, and Werner, a German soldier. As the war unfolds, Marie-Laure escapes Paris and finds refuge in a coastal town with her uncle, while Werner is recruited into the German army. Their lives intersect in a small French town, where the effects of war and the hope for survival reveal the human spirit’s resilience.', 'Anthony Doerr', 'Historical Fiction', '2014', true),

                                                                                        ('The Book Thief', 'In Nazi Germany, a young girl named Liesel steals books to escape the horrors of war and death. As her family harbors a Jewish refugee, Liesel’s life is transformed by the power of words and the stories she tells. Her bond with her foster parents and the friendships she builds throughout the war are a testament to the strength of love, even in the darkest of times.', 'Markus Zusak', 'Historical Fiction', '2005', true),

                                                                                        -- Horror
                                                                                        ('It', 'In the small town of Derry, Maine, a group of children confront a terrifying force that preys on their fears. When the group, known as the Losers’ Club, reunites as adults years later, they discover that the nightmare they faced as children is not over. The evil entity, which takes the form of a terrifying clown named Pennywise, has returned, and the Losers must face their past to stop the horror once and for all.', 'Stephen King', 'Horror', '1986', false),

                                                                                        ('The Shining', 'Jack Torrance, a struggling writer, takes a job as the winter caretaker of the isolated Overlook Hotel. He moves there with his wife Wendy and his son Danny, who has psychic abilities. As the isolation of the hotel takes its toll, Jack begins to lose his sanity, influenced by supernatural forces. Danny, with his psychic powers, must find a way to protect himself and his mother from Jack’s increasingly violent tendencies.', 'Stephen King', 'Horror', '1977', true),

                                                                                        -- Romance
                                                                                        ('Me Before You', 'Louisa Clark, a quirky and optimistic young woman, takes a job as a caregiver to Will Traynor, a wealthy man who is paralyzed after a motorcycle accident. As they spend time together, Louisa’s cheerful attitude and Will’s dark sense of humor begin to change each other’s lives. What starts as an unlikely friendship soon becomes a deep, transformative love, challenging both Louisa and Will to reconsider their views on life and death.', 'Jojo Moyes', 'Romance', '2012', true),

                                                                                        ('The Fault in Our Stars', 'Hazel Grace Lancaster, a sixteen-year-old cancer survivor, meets Augustus Waters, a charming boy who is also battling cancer. They form a deep bond over their shared experiences and their love of literature, particularly a novel that has no ending. As their relationship deepens, they face the harsh realities of their illnesses, but their love remains a bright light in the midst of hardship.', 'John Green', 'Romance', '2012', false);

INSERT INTO users (name, email, password) VALUES ('admin', 'admin@example.com', '$2a$10$2A2Bq/THOc3Ln8j1EemUJOKvGpZOgOqC50XO7HB8r1xvcN6ZV/umW');
